# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fZqYj9UQHM95xEXsW+fn/CFAyttQSWWYcV5RbzKYRc1FlDMgpLk5/kk3+xNnRw24v0NKpAHFAVx48dPaJCf4V7PWAuy7R5aRYsU7xmxqvhxjxd0DTeOvwg4x3+UvuIEP7NFDap0gJQxDmRcsWjoTochLueQN2cytkk/0n0X5JWJlw9BOkLndZ6QiM6h3XekFSttP5IbtQuDvdebyF1dNbR7QhHUFWyb2YsDf6Xg30aZbQArmAgY+XcgpiFBshyMToAkCYgWRN5spcnB1jz2HXT3YOJuYB1PxlYaRZeFLvXGUsl95AKPIaaKqo9p76p3MSSDXccFY/RBq/21tf7jjpQ9NJjcYt+jm1SmLXF++9+ia0uPNuxt5HsFxOPfEaUi+rWHnqh8GZj8L8YXsmVC4xkS0YecoovoMYPzj9CpoPQh1VhmWZQCSh9oecNDhNzZ7xf3A3RUIkhrjn2MsxjjqehuphxAmI83wvZBsaY+CtRYACMUZ+O8nXfRvf3Fu7aGPzthnmFpcOFlKxLTIhqUBPi+J0uAdU4J1Wz/HXQjm9ylPSP0m/B1JDkqqYOyO2mK1x3uDf6QkRVjbAOV35jjQnc/w17HnX83g3DftSxPgrcirSNIfU5l9aOvSWZ9tnlq2rJIW2STJIH8jjQW6FRi3E1PhgxBYyS5JaWhKqWm5GUk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml